// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteOrganizationOrganizationIDParams creates a new DeleteOrganizationOrganizationIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteOrganizationOrganizationIDParams() *DeleteOrganizationOrganizationIDParams {
	return &DeleteOrganizationOrganizationIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrganizationOrganizationIDParamsWithTimeout creates a new DeleteOrganizationOrganizationIDParams object
// with the ability to set a timeout on a request.
func NewDeleteOrganizationOrganizationIDParamsWithTimeout(timeout time.Duration) *DeleteOrganizationOrganizationIDParams {
	return &DeleteOrganizationOrganizationIDParams{
		timeout: timeout,
	}
}

// NewDeleteOrganizationOrganizationIDParamsWithContext creates a new DeleteOrganizationOrganizationIDParams object
// with the ability to set a context for a request.
func NewDeleteOrganizationOrganizationIDParamsWithContext(ctx context.Context) *DeleteOrganizationOrganizationIDParams {
	return &DeleteOrganizationOrganizationIDParams{
		Context: ctx,
	}
}

// NewDeleteOrganizationOrganizationIDParamsWithHTTPClient creates a new DeleteOrganizationOrganizationIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteOrganizationOrganizationIDParamsWithHTTPClient(client *http.Client) *DeleteOrganizationOrganizationIDParams {
	return &DeleteOrganizationOrganizationIDParams{
		HTTPClient: client,
	}
}

/* DeleteOrganizationOrganizationIDParams contains all the parameters to send to the API endpoint
   for the delete organization organization ID operation.

   Typically these are written to a http.Request.
*/
type DeleteOrganizationOrganizationIDParams struct {

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete organization organization ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrganizationOrganizationIDParams) WithDefaults() *DeleteOrganizationOrganizationIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete organization organization ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrganizationOrganizationIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete organization organization ID params
func (o *DeleteOrganizationOrganizationIDParams) WithTimeout(timeout time.Duration) *DeleteOrganizationOrganizationIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete organization organization ID params
func (o *DeleteOrganizationOrganizationIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete organization organization ID params
func (o *DeleteOrganizationOrganizationIDParams) WithContext(ctx context.Context) *DeleteOrganizationOrganizationIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete organization organization ID params
func (o *DeleteOrganizationOrganizationIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete organization organization ID params
func (o *DeleteOrganizationOrganizationIDParams) WithHTTPClient(client *http.Client) *DeleteOrganizationOrganizationIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete organization organization ID params
func (o *DeleteOrganizationOrganizationIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the delete organization organization ID params
func (o *DeleteOrganizationOrganizationIDParams) WithOrganizationID(organizationID string) *DeleteOrganizationOrganizationIDParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the delete organization organization ID params
func (o *DeleteOrganizationOrganizationIDParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrganizationOrganizationIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
