// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteOrganizationOrganizationIDReader is a Reader for the DeleteOrganizationOrganizationID structure.
type DeleteOrganizationOrganizationIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrganizationOrganizationIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteOrganizationOrganizationIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteOrganizationOrganizationIDNoContent creates a DeleteOrganizationOrganizationIDNoContent with default headers values
func NewDeleteOrganizationOrganizationIDNoContent() *DeleteOrganizationOrganizationIDNoContent {
	return &DeleteOrganizationOrganizationIDNoContent{}
}

/* DeleteOrganizationOrganizationIDNoContent describes a response with status code 204, with default header values.

Successful response
*/
type DeleteOrganizationOrganizationIDNoContent struct {
}

func (o *DeleteOrganizationOrganizationIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /organization/{organizationId}][%d] deleteOrganizationOrganizationIdNoContent ", 204)
}

func (o *DeleteOrganizationOrganizationIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
