// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostOrganizationParams creates a new PostOrganizationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOrganizationParams() *PostOrganizationParams {
	return &PostOrganizationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganizationParamsWithTimeout creates a new PostOrganizationParams object
// with the ability to set a timeout on a request.
func NewPostOrganizationParamsWithTimeout(timeout time.Duration) *PostOrganizationParams {
	return &PostOrganizationParams{
		timeout: timeout,
	}
}

// NewPostOrganizationParamsWithContext creates a new PostOrganizationParams object
// with the ability to set a context for a request.
func NewPostOrganizationParamsWithContext(ctx context.Context) *PostOrganizationParams {
	return &PostOrganizationParams{
		Context: ctx,
	}
}

// NewPostOrganizationParamsWithHTTPClient creates a new PostOrganizationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOrganizationParamsWithHTTPClient(client *http.Client) *PostOrganizationParams {
	return &PostOrganizationParams{
		HTTPClient: client,
	}
}

/* PostOrganizationParams contains all the parameters to send to the API endpoint
   for the post organization operation.

   Typically these are written to a http.Request.
*/
type PostOrganizationParams struct {

	// Organization.
	Organization PostOrganizationBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post organization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationParams) WithDefaults() *PostOrganizationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post organization params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post organization params
func (o *PostOrganizationParams) WithTimeout(timeout time.Duration) *PostOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organization params
func (o *PostOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organization params
func (o *PostOrganizationParams) WithContext(ctx context.Context) *PostOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organization params
func (o *PostOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post organization params
func (o *PostOrganizationParams) WithHTTPClient(client *http.Client) *PostOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post organization params
func (o *PostOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the post organization params
func (o *PostOrganizationParams) WithOrganization(organization PostOrganizationBody) *PostOrganizationParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the post organization params
func (o *PostOrganizationParams) SetOrganization(organization PostOrganizationBody) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
