// Code generated by go-swagger; DO NOT EDIT.

package module

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteOrganizationOrganizationIDRelationshipsModuleParams creates a new DeleteOrganizationOrganizationIDRelationshipsModuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteOrganizationOrganizationIDRelationshipsModuleParams() *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	return &DeleteOrganizationOrganizationIDRelationshipsModuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrganizationOrganizationIDRelationshipsModuleParamsWithTimeout creates a new DeleteOrganizationOrganizationIDRelationshipsModuleParams object
// with the ability to set a timeout on a request.
func NewDeleteOrganizationOrganizationIDRelationshipsModuleParamsWithTimeout(timeout time.Duration) *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	return &DeleteOrganizationOrganizationIDRelationshipsModuleParams{
		timeout: timeout,
	}
}

// NewDeleteOrganizationOrganizationIDRelationshipsModuleParamsWithContext creates a new DeleteOrganizationOrganizationIDRelationshipsModuleParams object
// with the ability to set a context for a request.
func NewDeleteOrganizationOrganizationIDRelationshipsModuleParamsWithContext(ctx context.Context) *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	return &DeleteOrganizationOrganizationIDRelationshipsModuleParams{
		Context: ctx,
	}
}

// NewDeleteOrganizationOrganizationIDRelationshipsModuleParamsWithHTTPClient creates a new DeleteOrganizationOrganizationIDRelationshipsModuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteOrganizationOrganizationIDRelationshipsModuleParamsWithHTTPClient(client *http.Client) *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	return &DeleteOrganizationOrganizationIDRelationshipsModuleParams{
		HTTPClient: client,
	}
}

/* DeleteOrganizationOrganizationIDRelationshipsModuleParams contains all the parameters to send to the API endpoint
   for the delete organization organization ID relationships module operation.

   Typically these are written to a http.Request.
*/
type DeleteOrganizationOrganizationIDRelationshipsModuleParams struct {

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	// Relationship.
	Relationship DeleteOrganizationOrganizationIDRelationshipsModuleBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete organization organization ID relationships module params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) WithDefaults() *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete organization organization ID relationships module params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) WithTimeout(timeout time.Duration) *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) WithContext(ctx context.Context) *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) WithHTTPClient(client *http.Client) *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) WithOrganizationID(organizationID string) *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithRelationship adds the relationship to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) WithRelationship(relationship DeleteOrganizationOrganizationIDRelationshipsModuleBody) *DeleteOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetRelationship(relationship)
	return o
}

// SetRelationship adds the relationship to the delete organization organization ID relationships module params
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) SetRelationship(relationship DeleteOrganizationOrganizationIDRelationshipsModuleBody) {
	o.Relationship = relationship
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Relationship); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
