// Code generated by go-swagger; DO NOT EDIT.

package module

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteOrganizationOrganizationIDRelationshipsModuleReader is a Reader for the DeleteOrganizationOrganizationIDRelationshipsModule structure.
type DeleteOrganizationOrganizationIDRelationshipsModuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteOrganizationOrganizationIDRelationshipsModuleNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteOrganizationOrganizationIDRelationshipsModuleNoContent creates a DeleteOrganizationOrganizationIDRelationshipsModuleNoContent with default headers values
func NewDeleteOrganizationOrganizationIDRelationshipsModuleNoContent() *DeleteOrganizationOrganizationIDRelationshipsModuleNoContent {
	return &DeleteOrganizationOrganizationIDRelationshipsModuleNoContent{}
}

/* DeleteOrganizationOrganizationIDRelationshipsModuleNoContent describes a response with status code 204, with default header values.

Successful response
*/
type DeleteOrganizationOrganizationIDRelationshipsModuleNoContent struct {
}

func (o *DeleteOrganizationOrganizationIDRelationshipsModuleNoContent) Error() string {
	return fmt.Sprintf("[DELETE /organization/{organizationId}/relationships/module][%d] deleteOrganizationOrganizationIdRelationshipsModuleNoContent ", 204)
}

func (o *DeleteOrganizationOrganizationIDRelationshipsModuleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*DeleteOrganizationOrganizationIDRelationshipsModuleBody delete organization organization ID relationships module body
swagger:model DeleteOrganizationOrganizationIDRelationshipsModuleBody
*/
type DeleteOrganizationOrganizationIDRelationshipsModuleBody struct {

	// data
	Data []*DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0 `json:"data"`
}

// Validate validates this delete organization organization ID relationships module body
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteOrganizationOrganizationIDRelationshipsModuleBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("relationship" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this delete organization organization ID relationships module body based on the context it is used
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteOrganizationOrganizationIDRelationshipsModuleBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("relationship" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleBody) UnmarshalBinary(b []byte) error {
	var res DeleteOrganizationOrganizationIDRelationshipsModuleBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0 delete organization organization ID relationships module params body data items0
swagger:model DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0
*/
type DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0 struct {

	// id
	ID string `json:"id,omitempty"`

	// type
	// Enum: [module]
	Type string `json:"type,omitempty"`
}

// Validate validates this delete organization organization ID relationships module params body data items0
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var deleteOrganizationOrganizationIdRelationshipsModuleParamsBodyDataItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["module"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteOrganizationOrganizationIdRelationshipsModuleParamsBodyDataItems0TypeTypePropEnum = append(deleteOrganizationOrganizationIdRelationshipsModuleParamsBodyDataItems0TypeTypePropEnum, v)
	}
}

const (

	// DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0TypeModule captures enum value "module"
	DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0TypeModule string = "module"
)

// prop value enum
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteOrganizationOrganizationIdRelationshipsModuleParamsBodyDataItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0) validateType(formats strfmt.Registry) error {
	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete organization organization ID relationships module params body data items0 based on context it is used
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res DeleteOrganizationOrganizationIDRelationshipsModuleParamsBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
