// Code generated by go-swagger; DO NOT EDIT.

package module

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationOrganizationIDRelationshipsModuleParams creates a new GetOrganizationOrganizationIDRelationshipsModuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationOrganizationIDRelationshipsModuleParams() *GetOrganizationOrganizationIDRelationshipsModuleParams {
	return &GetOrganizationOrganizationIDRelationshipsModuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationOrganizationIDRelationshipsModuleParamsWithTimeout creates a new GetOrganizationOrganizationIDRelationshipsModuleParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationOrganizationIDRelationshipsModuleParamsWithTimeout(timeout time.Duration) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	return &GetOrganizationOrganizationIDRelationshipsModuleParams{
		timeout: timeout,
	}
}

// NewGetOrganizationOrganizationIDRelationshipsModuleParamsWithContext creates a new GetOrganizationOrganizationIDRelationshipsModuleParams object
// with the ability to set a context for a request.
func NewGetOrganizationOrganizationIDRelationshipsModuleParamsWithContext(ctx context.Context) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	return &GetOrganizationOrganizationIDRelationshipsModuleParams{
		Context: ctx,
	}
}

// NewGetOrganizationOrganizationIDRelationshipsModuleParamsWithHTTPClient creates a new GetOrganizationOrganizationIDRelationshipsModuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationOrganizationIDRelationshipsModuleParamsWithHTTPClient(client *http.Client) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	return &GetOrganizationOrganizationIDRelationshipsModuleParams{
		HTTPClient: client,
	}
}

/* GetOrganizationOrganizationIDRelationshipsModuleParams contains all the parameters to send to the API endpoint
   for the get organization organization ID relationships module operation.

   Typically these are written to a http.Request.
*/
type GetOrganizationOrganizationIDRelationshipsModuleParams struct {

	/* FilterModule.

	   Filters the collection of module using a 'disjoint' RSQL expression
	*/
	FilterModule *string

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	/* PageLimit.

	   Maximum number of items to return.  Can be used with page[offset]
	*/
	PageLimit *int64

	/* PageNumber.

	   Number of pages to return.  Can be used with page[size]
	*/
	PageNumber *int64

	/* PageOffset.

	   Offset from 0 to start paginating.  Can be used with page[limit]
	*/
	PageOffset *int64

	/* PageSize.

	   Number of elements per page.  Can be used with page[number]
	*/
	PageSize *int64

	/* PageTotals.

	   For requesting total pages/records be included in the response page meta data
	*/
	PageTotals *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organization organization ID relationships module params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithDefaults() *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organization organization ID relationships module params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithTimeout(timeout time.Duration) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithContext(ctx context.Context) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithHTTPClient(client *http.Client) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilterModule adds the filterModule to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithFilterModule(filterModule *string) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetFilterModule(filterModule)
	return o
}

// SetFilterModule adds the filterModule to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetFilterModule(filterModule *string) {
	o.FilterModule = filterModule
}

// WithOrganizationID adds the organizationID to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithOrganizationID(organizationID string) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithPageLimit adds the pageLimit to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithPageLimit(pageLimit *int64) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetPageLimit(pageLimit)
	return o
}

// SetPageLimit adds the pageLimit to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetPageLimit(pageLimit *int64) {
	o.PageLimit = pageLimit
}

// WithPageNumber adds the pageNumber to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithPageNumber(pageNumber *int64) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetPageNumber(pageNumber)
	return o
}

// SetPageNumber adds the pageNumber to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetPageNumber(pageNumber *int64) {
	o.PageNumber = pageNumber
}

// WithPageOffset adds the pageOffset to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithPageOffset(pageOffset *int64) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetPageOffset(pageOffset)
	return o
}

// SetPageOffset adds the pageOffset to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetPageOffset(pageOffset *int64) {
	o.PageOffset = pageOffset
}

// WithPageSize adds the pageSize to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithPageSize(pageSize *int64) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithPageTotals adds the pageTotals to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WithPageTotals(pageTotals *string) *GetOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetPageTotals(pageTotals)
	return o
}

// SetPageTotals adds the pageTotals to the get organization organization ID relationships module params
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) SetPageTotals(pageTotals *string) {
	o.PageTotals = pageTotals
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationOrganizationIDRelationshipsModuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FilterModule != nil {

		// query param filter[module]
		var qrFilterModule string

		if o.FilterModule != nil {
			qrFilterModule = *o.FilterModule
		}
		qFilterModule := qrFilterModule
		if qFilterModule != "" {

			if err := r.SetQueryParam("filter[module]", qFilterModule); err != nil {
				return err
			}
		}
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if o.PageLimit != nil {

		// query param page[limit]
		var qrPageLimit int64

		if o.PageLimit != nil {
			qrPageLimit = *o.PageLimit
		}
		qPageLimit := swag.FormatInt64(qrPageLimit)
		if qPageLimit != "" {

			if err := r.SetQueryParam("page[limit]", qPageLimit); err != nil {
				return err
			}
		}
	}

	if o.PageNumber != nil {

		// query param page[number]
		var qrPageNumber int64

		if o.PageNumber != nil {
			qrPageNumber = *o.PageNumber
		}
		qPageNumber := swag.FormatInt64(qrPageNumber)
		if qPageNumber != "" {

			if err := r.SetQueryParam("page[number]", qPageNumber); err != nil {
				return err
			}
		}
	}

	if o.PageOffset != nil {

		// query param page[offset]
		var qrPageOffset int64

		if o.PageOffset != nil {
			qrPageOffset = *o.PageOffset
		}
		qPageOffset := swag.FormatInt64(qrPageOffset)
		if qPageOffset != "" {

			if err := r.SetQueryParam("page[offset]", qPageOffset); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page[size]
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page[size]", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.PageTotals != nil {

		// query param page[totals]
		var qrPageTotals string

		if o.PageTotals != nil {
			qrPageTotals = *o.PageTotals
		}
		qPageTotals := qrPageTotals
		if qPageTotals != "" {

			if err := r.SetQueryParam("page[totals]", qPageTotals); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
