// Code generated by go-swagger; DO NOT EDIT.

package module

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetOrganizationOrganizationIDRelationshipsModuleReader is a Reader for the GetOrganizationOrganizationIDRelationshipsModule structure.
type GetOrganizationOrganizationIDRelationshipsModuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationOrganizationIDRelationshipsModuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationOrganizationIDRelationshipsModuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationOrganizationIDRelationshipsModuleOK creates a GetOrganizationOrganizationIDRelationshipsModuleOK with default headers values
func NewGetOrganizationOrganizationIDRelationshipsModuleOK() *GetOrganizationOrganizationIDRelationshipsModuleOK {
	return &GetOrganizationOrganizationIDRelationshipsModuleOK{}
}

/* GetOrganizationOrganizationIDRelationshipsModuleOK describes a response with status code 200, with default header values.

Successful response
*/
type GetOrganizationOrganizationIDRelationshipsModuleOK struct {
	Payload *GetOrganizationOrganizationIDRelationshipsModuleOKBody
}

func (o *GetOrganizationOrganizationIDRelationshipsModuleOK) Error() string {
	return fmt.Sprintf("[GET /organization/{organizationId}/relationships/module][%d] getOrganizationOrganizationIdRelationshipsModuleOK  %+v", 200, o.Payload)
}
func (o *GetOrganizationOrganizationIDRelationshipsModuleOK) GetPayload() *GetOrganizationOrganizationIDRelationshipsModuleOKBody {
	return o.Payload
}

func (o *GetOrganizationOrganizationIDRelationshipsModuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetOrganizationOrganizationIDRelationshipsModuleOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetOrganizationOrganizationIDRelationshipsModuleOKBody get organization organization ID relationships module o k body
swagger:model GetOrganizationOrganizationIDRelationshipsModuleOKBody
*/
type GetOrganizationOrganizationIDRelationshipsModuleOKBody struct {

	// data
	Data []*GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0 `json:"data"`
}

// Validate validates this get organization organization ID relationships module o k body
func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOrganizationOrganizationIdRelationshipsModuleOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get organization organization ID relationships module o k body based on the context it is used
func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOrganizationOrganizationIdRelationshipsModuleOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBody) UnmarshalBinary(b []byte) error {
	var res GetOrganizationOrganizationIDRelationshipsModuleOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0 get organization organization ID relationships module o k body data items0
swagger:model GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0
*/
type GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0 struct {

	// id
	ID string `json:"id,omitempty"`

	// type
	// Enum: [module]
	Type string `json:"type,omitempty"`
}

// Validate validates this get organization organization ID relationships module o k body data items0
func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getOrganizationOrganizationIdRelationshipsModuleOKBodyDataItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["module"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getOrganizationOrganizationIdRelationshipsModuleOKBodyDataItems0TypeTypePropEnum = append(getOrganizationOrganizationIdRelationshipsModuleOKBodyDataItems0TypeTypePropEnum, v)
	}
}

const (

	// GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0TypeModule captures enum value "module"
	GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0TypeModule string = "module"
)

// prop value enum
func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getOrganizationOrganizationIdRelationshipsModuleOKBodyDataItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0) validateType(formats strfmt.Registry) error {
	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get organization organization ID relationships module o k body data items0 based on context it is used
func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res GetOrganizationOrganizationIDRelationshipsModuleOKBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
