// Code generated by go-swagger; DO NOT EDIT.

package module

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"azb/client/models"
)

// GetOrganizationOrganizationIDModuleModuleIDReader is a Reader for the GetOrganizationOrganizationIDModuleModuleID structure.
type GetOrganizationOrganizationIDModuleModuleIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationOrganizationIDModuleModuleIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationOrganizationIDModuleModuleIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationOrganizationIDModuleModuleIDOK creates a GetOrganizationOrganizationIDModuleModuleIDOK with default headers values
func NewGetOrganizationOrganizationIDModuleModuleIDOK() *GetOrganizationOrganizationIDModuleModuleIDOK {
	return &GetOrganizationOrganizationIDModuleModuleIDOK{}
}

/* GetOrganizationOrganizationIDModuleModuleIDOK describes a response with status code 200, with default header values.

Successful response
*/
type GetOrganizationOrganizationIDModuleModuleIDOK struct {
	Payload *GetOrganizationOrganizationIDModuleModuleIDOKBody
}

func (o *GetOrganizationOrganizationIDModuleModuleIDOK) Error() string {
	return fmt.Sprintf("[GET /organization/{organizationId}/module/{moduleId}][%d] getOrganizationOrganizationIdModuleModuleIdOK  %+v", 200, o.Payload)
}
func (o *GetOrganizationOrganizationIDModuleModuleIDOK) GetPayload() *GetOrganizationOrganizationIDModuleModuleIDOKBody {
	return o.Payload
}

func (o *GetOrganizationOrganizationIDModuleModuleIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetOrganizationOrganizationIDModuleModuleIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetOrganizationOrganizationIDModuleModuleIDOKBody get organization organization ID module module ID o k body
swagger:model GetOrganizationOrganizationIDModuleModuleIDOKBody
*/
type GetOrganizationOrganizationIDModuleModuleIDOKBody struct {

	// data
	Data *models.Module `json:"data,omitempty"`

	// Included resources
	// Unique: true
	Included []*GetOrganizationOrganizationIDModuleModuleIDOKBodyIncludedItems0 `json:"included"`
}

// Validate validates this get organization organization ID module module ID o k body
func (o *GetOrganizationOrganizationIDModuleModuleIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIncluded(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOrganizationOrganizationIDModuleModuleIDOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getOrganizationOrganizationIdModuleModuleIdOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

func (o *GetOrganizationOrganizationIDModuleModuleIDOKBody) validateIncluded(formats strfmt.Registry) error {
	if swag.IsZero(o.Included) { // not required
		return nil
	}

	if err := validate.UniqueItems("getOrganizationOrganizationIdModuleModuleIdOK"+"."+"included", "body", o.Included); err != nil {
		return err
	}

	for i := 0; i < len(o.Included); i++ {
		if swag.IsZero(o.Included[i]) { // not required
			continue
		}

		if o.Included[i] != nil {
			if err := o.Included[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOrganizationOrganizationIdModuleModuleIdOK" + "." + "included" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get organization organization ID module module ID o k body based on the context it is used
func (o *GetOrganizationOrganizationIDModuleModuleIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateIncluded(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOrganizationOrganizationIDModuleModuleIDOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getOrganizationOrganizationIdModuleModuleIdOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

func (o *GetOrganizationOrganizationIDModuleModuleIDOKBody) contextValidateIncluded(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Included); i++ {

		if o.Included[i] != nil {
			if err := o.Included[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOrganizationOrganizationIdModuleModuleIdOK" + "." + "included" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDModuleModuleIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDModuleModuleIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetOrganizationOrganizationIDModuleModuleIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetOrganizationOrganizationIDModuleModuleIDOKBodyIncludedItems0 get organization organization ID module module ID o k body included items0
swagger:model GetOrganizationOrganizationIDModuleModuleIDOKBodyIncludedItems0
*/
type GetOrganizationOrganizationIDModuleModuleIDOKBodyIncludedItems0 struct {

	// attributes
	Attributes interface{} `json:"attributes,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// relationships
	Relationships interface{} `json:"relationships,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this get organization organization ID module module ID o k body included items0
func (o *GetOrganizationOrganizationIDModuleModuleIDOKBodyIncludedItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get organization organization ID module module ID o k body included items0 based on context it is used
func (o *GetOrganizationOrganizationIDModuleModuleIDOKBodyIncludedItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDModuleModuleIDOKBodyIncludedItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDModuleModuleIDOKBodyIncludedItems0) UnmarshalBinary(b []byte) error {
	var res GetOrganizationOrganizationIDModuleModuleIDOKBodyIncludedItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
