// Code generated by go-swagger; DO NOT EDIT.

package module

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"azb/client/models"
)

// PatchOrganizationOrganizationIDModuleModuleIDReader is a Reader for the PatchOrganizationOrganizationIDModuleModuleID structure.
type PatchOrganizationOrganizationIDModuleModuleIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchOrganizationOrganizationIDModuleModuleIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPatchOrganizationOrganizationIDModuleModuleIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchOrganizationOrganizationIDModuleModuleIDNoContent creates a PatchOrganizationOrganizationIDModuleModuleIDNoContent with default headers values
func NewPatchOrganizationOrganizationIDModuleModuleIDNoContent() *PatchOrganizationOrganizationIDModuleModuleIDNoContent {
	return &PatchOrganizationOrganizationIDModuleModuleIDNoContent{}
}

/* PatchOrganizationOrganizationIDModuleModuleIDNoContent describes a response with status code 204, with default header values.

Successful response
*/
type PatchOrganizationOrganizationIDModuleModuleIDNoContent struct {
}

func (o *PatchOrganizationOrganizationIDModuleModuleIDNoContent) Error() string {
	return fmt.Sprintf("[PATCH /organization/{organizationId}/module/{moduleId}][%d] patchOrganizationOrganizationIdModuleModuleIdNoContent ", 204)
}

func (o *PatchOrganizationOrganizationIDModuleModuleIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PatchOrganizationOrganizationIDModuleModuleIDBody patch organization organization ID module module ID body
swagger:model PatchOrganizationOrganizationIDModuleModuleIDBody
*/
type PatchOrganizationOrganizationIDModuleModuleIDBody struct {

	// data
	Data *models.Module `json:"data,omitempty"`
}

// Validate validates this patch organization organization ID module module ID body
func (o *PatchOrganizationOrganizationIDModuleModuleIDBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchOrganizationOrganizationIDModuleModuleIDBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("module" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this patch organization organization ID module module ID body based on the context it is used
func (o *PatchOrganizationOrganizationIDModuleModuleIDBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchOrganizationOrganizationIDModuleModuleIDBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("module" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PatchOrganizationOrganizationIDModuleModuleIDBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PatchOrganizationOrganizationIDModuleModuleIDBody) UnmarshalBinary(b []byte) error {
	var res PatchOrganizationOrganizationIDModuleModuleIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
