// Code generated by go-swagger; DO NOT EDIT.

package module

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"azb/client/models"
)

// PostOrganizationOrganizationIDModuleReader is a Reader for the PostOrganizationOrganizationIDModule structure.
type PostOrganizationOrganizationIDModuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOrganizationOrganizationIDModuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostOrganizationOrganizationIDModuleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostOrganizationOrganizationIDModuleCreated creates a PostOrganizationOrganizationIDModuleCreated with default headers values
func NewPostOrganizationOrganizationIDModuleCreated() *PostOrganizationOrganizationIDModuleCreated {
	return &PostOrganizationOrganizationIDModuleCreated{}
}

/* PostOrganizationOrganizationIDModuleCreated describes a response with status code 201, with default header values.

Successful response
*/
type PostOrganizationOrganizationIDModuleCreated struct {
	Payload *PostOrganizationOrganizationIDModuleCreatedBody
}

func (o *PostOrganizationOrganizationIDModuleCreated) Error() string {
	return fmt.Sprintf("[POST /organization/{organizationId}/module][%d] postOrganizationOrganizationIdModuleCreated  %+v", 201, o.Payload)
}
func (o *PostOrganizationOrganizationIDModuleCreated) GetPayload() *PostOrganizationOrganizationIDModuleCreatedBody {
	return o.Payload
}

func (o *PostOrganizationOrganizationIDModuleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostOrganizationOrganizationIDModuleCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostOrganizationOrganizationIDModuleBody post organization organization ID module body
swagger:model PostOrganizationOrganizationIDModuleBody
*/
type PostOrganizationOrganizationIDModuleBody struct {

	// data
	Data *models.Module `json:"data,omitempty"`
}

// Validate validates this post organization organization ID module body
func (o *PostOrganizationOrganizationIDModuleBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationOrganizationIDModuleBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("module" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post organization organization ID module body based on the context it is used
func (o *PostOrganizationOrganizationIDModuleBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationOrganizationIDModuleBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("module" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDModuleBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDModuleBody) UnmarshalBinary(b []byte) error {
	var res PostOrganizationOrganizationIDModuleBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostOrganizationOrganizationIDModuleCreatedBody post organization organization ID module created body
swagger:model PostOrganizationOrganizationIDModuleCreatedBody
*/
type PostOrganizationOrganizationIDModuleCreatedBody struct {

	// data
	Data *models.Module `json:"data,omitempty"`
}

// Validate validates this post organization organization ID module created body
func (o *PostOrganizationOrganizationIDModuleCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationOrganizationIDModuleCreatedBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postOrganizationOrganizationIdModuleCreated" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post organization organization ID module created body based on the context it is used
func (o *PostOrganizationOrganizationIDModuleCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationOrganizationIDModuleCreatedBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postOrganizationOrganizationIdModuleCreated" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDModuleCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDModuleCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostOrganizationOrganizationIDModuleCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
