// Code generated by go-swagger; DO NOT EDIT.

package module

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostOrganizationOrganizationIDRelationshipsModuleParams creates a new PostOrganizationOrganizationIDRelationshipsModuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOrganizationOrganizationIDRelationshipsModuleParams() *PostOrganizationOrganizationIDRelationshipsModuleParams {
	return &PostOrganizationOrganizationIDRelationshipsModuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganizationOrganizationIDRelationshipsModuleParamsWithTimeout creates a new PostOrganizationOrganizationIDRelationshipsModuleParams object
// with the ability to set a timeout on a request.
func NewPostOrganizationOrganizationIDRelationshipsModuleParamsWithTimeout(timeout time.Duration) *PostOrganizationOrganizationIDRelationshipsModuleParams {
	return &PostOrganizationOrganizationIDRelationshipsModuleParams{
		timeout: timeout,
	}
}

// NewPostOrganizationOrganizationIDRelationshipsModuleParamsWithContext creates a new PostOrganizationOrganizationIDRelationshipsModuleParams object
// with the ability to set a context for a request.
func NewPostOrganizationOrganizationIDRelationshipsModuleParamsWithContext(ctx context.Context) *PostOrganizationOrganizationIDRelationshipsModuleParams {
	return &PostOrganizationOrganizationIDRelationshipsModuleParams{
		Context: ctx,
	}
}

// NewPostOrganizationOrganizationIDRelationshipsModuleParamsWithHTTPClient creates a new PostOrganizationOrganizationIDRelationshipsModuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOrganizationOrganizationIDRelationshipsModuleParamsWithHTTPClient(client *http.Client) *PostOrganizationOrganizationIDRelationshipsModuleParams {
	return &PostOrganizationOrganizationIDRelationshipsModuleParams{
		HTTPClient: client,
	}
}

/* PostOrganizationOrganizationIDRelationshipsModuleParams contains all the parameters to send to the API endpoint
   for the post organization organization ID relationships module operation.

   Typically these are written to a http.Request.
*/
type PostOrganizationOrganizationIDRelationshipsModuleParams struct {

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	// Relationship.
	Relationship PostOrganizationOrganizationIDRelationshipsModuleBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post organization organization ID relationships module params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) WithDefaults() *PostOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post organization organization ID relationships module params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) WithTimeout(timeout time.Duration) *PostOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) WithContext(ctx context.Context) *PostOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) WithHTTPClient(client *http.Client) *PostOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) WithOrganizationID(organizationID string) *PostOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithRelationship adds the relationship to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) WithRelationship(relationship PostOrganizationOrganizationIDRelationshipsModuleBody) *PostOrganizationOrganizationIDRelationshipsModuleParams {
	o.SetRelationship(relationship)
	return o
}

// SetRelationship adds the relationship to the post organization organization ID relationships module params
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) SetRelationship(relationship PostOrganizationOrganizationIDRelationshipsModuleBody) {
	o.Relationship = relationship
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganizationOrganizationIDRelationshipsModuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Relationship); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
