// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetOrganizationOrganizationIDRelationshipsWorkspaceReader is a Reader for the GetOrganizationOrganizationIDRelationshipsWorkspace structure.
type GetOrganizationOrganizationIDRelationshipsWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationOrganizationIDRelationshipsWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationOrganizationIDRelationshipsWorkspaceOK creates a GetOrganizationOrganizationIDRelationshipsWorkspaceOK with default headers values
func NewGetOrganizationOrganizationIDRelationshipsWorkspaceOK() *GetOrganizationOrganizationIDRelationshipsWorkspaceOK {
	return &GetOrganizationOrganizationIDRelationshipsWorkspaceOK{}
}

/* GetOrganizationOrganizationIDRelationshipsWorkspaceOK describes a response with status code 200, with default header values.

Successful response
*/
type GetOrganizationOrganizationIDRelationshipsWorkspaceOK struct {
	Payload *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody
}

func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOK) Error() string {
	return fmt.Sprintf("[GET /organization/{organizationId}/relationships/workspace][%d] getOrganizationOrganizationIdRelationshipsWorkspaceOK  %+v", 200, o.Payload)
}
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOK) GetPayload() *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody {
	return o.Payload
}

func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody get organization organization ID relationships workspace o k body
swagger:model GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody
*/
type GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody struct {

	// data
	Data []*GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0 `json:"data"`
}

// Validate validates this get organization organization ID relationships workspace o k body
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOrganizationOrganizationIdRelationshipsWorkspaceOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get organization organization ID relationships workspace o k body based on the context it is used
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOrganizationOrganizationIdRelationshipsWorkspaceOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody) UnmarshalBinary(b []byte) error {
	var res GetOrganizationOrganizationIDRelationshipsWorkspaceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0 get organization organization ID relationships workspace o k body data items0
swagger:model GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0
*/
type GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0 struct {

	// id
	ID string `json:"id,omitempty"`

	// type
	// Enum: [workspace]
	Type string `json:"type,omitempty"`
}

// Validate validates this get organization organization ID relationships workspace o k body data items0
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getOrganizationOrganizationIdRelationshipsWorkspaceOKBodyDataItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["workspace"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getOrganizationOrganizationIdRelationshipsWorkspaceOKBodyDataItems0TypeTypePropEnum = append(getOrganizationOrganizationIdRelationshipsWorkspaceOKBodyDataItems0TypeTypePropEnum, v)
	}
}

const (

	// GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0TypeWorkspace captures enum value "workspace"
	GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0TypeWorkspace string = "workspace"
)

// prop value enum
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getOrganizationOrganizationIdRelationshipsWorkspaceOKBodyDataItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0) validateType(formats strfmt.Registry) error {
	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get organization organization ID relationships workspace o k body data items0 based on context it is used
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res GetOrganizationOrganizationIDRelationshipsWorkspaceOKBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
