// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchOrganizationOrganizationIDRelationshipsWorkspaceParams creates a new PatchOrganizationOrganizationIDRelationshipsWorkspaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchOrganizationOrganizationIDRelationshipsWorkspaceParams() *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	return &PatchOrganizationOrganizationIDRelationshipsWorkspaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchOrganizationOrganizationIDRelationshipsWorkspaceParamsWithTimeout creates a new PatchOrganizationOrganizationIDRelationshipsWorkspaceParams object
// with the ability to set a timeout on a request.
func NewPatchOrganizationOrganizationIDRelationshipsWorkspaceParamsWithTimeout(timeout time.Duration) *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	return &PatchOrganizationOrganizationIDRelationshipsWorkspaceParams{
		timeout: timeout,
	}
}

// NewPatchOrganizationOrganizationIDRelationshipsWorkspaceParamsWithContext creates a new PatchOrganizationOrganizationIDRelationshipsWorkspaceParams object
// with the ability to set a context for a request.
func NewPatchOrganizationOrganizationIDRelationshipsWorkspaceParamsWithContext(ctx context.Context) *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	return &PatchOrganizationOrganizationIDRelationshipsWorkspaceParams{
		Context: ctx,
	}
}

// NewPatchOrganizationOrganizationIDRelationshipsWorkspaceParamsWithHTTPClient creates a new PatchOrganizationOrganizationIDRelationshipsWorkspaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchOrganizationOrganizationIDRelationshipsWorkspaceParamsWithHTTPClient(client *http.Client) *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	return &PatchOrganizationOrganizationIDRelationshipsWorkspaceParams{
		HTTPClient: client,
	}
}

/* PatchOrganizationOrganizationIDRelationshipsWorkspaceParams contains all the parameters to send to the API endpoint
   for the patch organization organization ID relationships workspace operation.

   Typically these are written to a http.Request.
*/
type PatchOrganizationOrganizationIDRelationshipsWorkspaceParams struct {

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	// Relationship.
	Relationship PatchOrganizationOrganizationIDRelationshipsWorkspaceBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch organization organization ID relationships workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) WithDefaults() *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch organization organization ID relationships workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) WithTimeout(timeout time.Duration) *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) WithContext(ctx context.Context) *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) WithHTTPClient(client *http.Client) *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) WithOrganizationID(organizationID string) *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithRelationship adds the relationship to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) WithRelationship(relationship PatchOrganizationOrganizationIDRelationshipsWorkspaceBody) *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams {
	o.SetRelationship(relationship)
	return o
}

// SetRelationship adds the relationship to the patch organization organization ID relationships workspace params
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) SetRelationship(relationship PatchOrganizationOrganizationIDRelationshipsWorkspaceBody) {
	o.Relationship = relationship
}

// WriteToRequest writes these params to a swagger request
func (o *PatchOrganizationOrganizationIDRelationshipsWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Relationship); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
