// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams creates a new PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams() *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	return &PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchOrganizationOrganizationIDWorkspaceWorkspaceIDParamsWithTimeout creates a new PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams object
// with the ability to set a timeout on a request.
func NewPatchOrganizationOrganizationIDWorkspaceWorkspaceIDParamsWithTimeout(timeout time.Duration) *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	return &PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams{
		timeout: timeout,
	}
}

// NewPatchOrganizationOrganizationIDWorkspaceWorkspaceIDParamsWithContext creates a new PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams object
// with the ability to set a context for a request.
func NewPatchOrganizationOrganizationIDWorkspaceWorkspaceIDParamsWithContext(ctx context.Context) *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	return &PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams{
		Context: ctx,
	}
}

// NewPatchOrganizationOrganizationIDWorkspaceWorkspaceIDParamsWithHTTPClient creates a new PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchOrganizationOrganizationIDWorkspaceWorkspaceIDParamsWithHTTPClient(client *http.Client) *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	return &PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams{
		HTTPClient: client,
	}
}

/* PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams contains all the parameters to send to the API endpoint
   for the patch organization organization ID workspace workspace ID operation.

   Typically these are written to a http.Request.
*/
type PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams struct {

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	// Workspace.
	Workspace PatchOrganizationOrganizationIDWorkspaceWorkspaceIDBody

	/* WorkspaceID.

	   workspace Identifier
	*/
	WorkspaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch organization organization ID workspace workspace ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) WithDefaults() *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch organization organization ID workspace workspace ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) WithTimeout(timeout time.Duration) *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) WithContext(ctx context.Context) *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) WithHTTPClient(client *http.Client) *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) WithOrganizationID(organizationID string) *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithWorkspace adds the workspace to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) WithWorkspace(workspace PatchOrganizationOrganizationIDWorkspaceWorkspaceIDBody) *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	o.SetWorkspace(workspace)
	return o
}

// SetWorkspace adds the workspace to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) SetWorkspace(workspace PatchOrganizationOrganizationIDWorkspaceWorkspaceIDBody) {
	o.Workspace = workspace
}

// WithWorkspaceID adds the workspaceID to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) WithWorkspaceID(workspaceID string) *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the patch organization organization ID workspace workspace ID params
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) SetWorkspaceID(workspaceID string) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchOrganizationOrganizationIDWorkspaceWorkspaceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Workspace); err != nil {
		return err
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", o.WorkspaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
