// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostOrganizationOrganizationIDRelationshipsWorkspaceReader is a Reader for the PostOrganizationOrganizationIDRelationshipsWorkspace structure.
type PostOrganizationOrganizationIDRelationshipsWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostOrganizationOrganizationIDRelationshipsWorkspaceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostOrganizationOrganizationIDRelationshipsWorkspaceCreated creates a PostOrganizationOrganizationIDRelationshipsWorkspaceCreated with default headers values
func NewPostOrganizationOrganizationIDRelationshipsWorkspaceCreated() *PostOrganizationOrganizationIDRelationshipsWorkspaceCreated {
	return &PostOrganizationOrganizationIDRelationshipsWorkspaceCreated{}
}

/* PostOrganizationOrganizationIDRelationshipsWorkspaceCreated describes a response with status code 201, with default header values.

Successful response
*/
type PostOrganizationOrganizationIDRelationshipsWorkspaceCreated struct {
	Payload *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody
}

func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreated) Error() string {
	return fmt.Sprintf("[POST /organization/{organizationId}/relationships/workspace][%d] postOrganizationOrganizationIdRelationshipsWorkspaceCreated  %+v", 201, o.Payload)
}
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreated) GetPayload() *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody {
	return o.Payload
}

func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostOrganizationOrganizationIDRelationshipsWorkspaceBody post organization organization ID relationships workspace body
swagger:model PostOrganizationOrganizationIDRelationshipsWorkspaceBody
*/
type PostOrganizationOrganizationIDRelationshipsWorkspaceBody struct {

	// data
	Data []*PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0 `json:"data"`
}

// Validate validates this post organization organization ID relationships workspace body
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("relationship" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this post organization organization ID relationships workspace body based on the context it is used
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("relationship" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceBody) UnmarshalBinary(b []byte) error {
	var res PostOrganizationOrganizationIDRelationshipsWorkspaceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody post organization organization ID relationships workspace created body
swagger:model PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody
*/
type PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody struct {

	// data
	Data []*PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0 `json:"data"`
}

// Validate validates this post organization organization ID relationships workspace created body
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("postOrganizationOrganizationIdRelationshipsWorkspaceCreated" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this post organization organization ID relationships workspace created body based on the context it is used
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("postOrganizationOrganizationIdRelationshipsWorkspaceCreated" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0 post organization organization ID relationships workspace created body data items0
swagger:model PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0
*/
type PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0 struct {

	// id
	ID string `json:"id,omitempty"`

	// type
	// Enum: [workspace]
	Type string `json:"type,omitempty"`
}

// Validate validates this post organization organization ID relationships workspace created body data items0
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postOrganizationOrganizationIdRelationshipsWorkspaceCreatedBodyDataItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["workspace"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postOrganizationOrganizationIdRelationshipsWorkspaceCreatedBodyDataItems0TypeTypePropEnum = append(postOrganizationOrganizationIdRelationshipsWorkspaceCreatedBodyDataItems0TypeTypePropEnum, v)
	}
}

const (

	// PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0TypeWorkspace captures enum value "workspace"
	PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0TypeWorkspace string = "workspace"
)

// prop value enum
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postOrganizationOrganizationIdRelationshipsWorkspaceCreatedBodyDataItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0) validateType(formats strfmt.Registry) error {
	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post organization organization ID relationships workspace created body data items0 based on context it is used
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res PostOrganizationOrganizationIDRelationshipsWorkspaceCreatedBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0 post organization organization ID relationships workspace params body data items0
swagger:model PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0
*/
type PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0 struct {

	// id
	ID string `json:"id,omitempty"`

	// type
	// Enum: [workspace]
	Type string `json:"type,omitempty"`
}

// Validate validates this post organization organization ID relationships workspace params body data items0
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postOrganizationOrganizationIdRelationshipsWorkspaceParamsBodyDataItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["workspace"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postOrganizationOrganizationIdRelationshipsWorkspaceParamsBodyDataItems0TypeTypePropEnum = append(postOrganizationOrganizationIdRelationshipsWorkspaceParamsBodyDataItems0TypeTypePropEnum, v)
	}
}

const (

	// PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0TypeWorkspace captures enum value "workspace"
	PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0TypeWorkspace string = "workspace"
)

// prop value enum
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postOrganizationOrganizationIdRelationshipsWorkspaceParamsBodyDataItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0) validateType(formats strfmt.Registry) error {
	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post organization organization ID relationships workspace params body data items0 based on context it is used
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res PostOrganizationOrganizationIDRelationshipsWorkspaceParamsBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
