// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostOrganizationOrganizationIDWorkspaceParams creates a new PostOrganizationOrganizationIDWorkspaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOrganizationOrganizationIDWorkspaceParams() *PostOrganizationOrganizationIDWorkspaceParams {
	return &PostOrganizationOrganizationIDWorkspaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganizationOrganizationIDWorkspaceParamsWithTimeout creates a new PostOrganizationOrganizationIDWorkspaceParams object
// with the ability to set a timeout on a request.
func NewPostOrganizationOrganizationIDWorkspaceParamsWithTimeout(timeout time.Duration) *PostOrganizationOrganizationIDWorkspaceParams {
	return &PostOrganizationOrganizationIDWorkspaceParams{
		timeout: timeout,
	}
}

// NewPostOrganizationOrganizationIDWorkspaceParamsWithContext creates a new PostOrganizationOrganizationIDWorkspaceParams object
// with the ability to set a context for a request.
func NewPostOrganizationOrganizationIDWorkspaceParamsWithContext(ctx context.Context) *PostOrganizationOrganizationIDWorkspaceParams {
	return &PostOrganizationOrganizationIDWorkspaceParams{
		Context: ctx,
	}
}

// NewPostOrganizationOrganizationIDWorkspaceParamsWithHTTPClient creates a new PostOrganizationOrganizationIDWorkspaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOrganizationOrganizationIDWorkspaceParamsWithHTTPClient(client *http.Client) *PostOrganizationOrganizationIDWorkspaceParams {
	return &PostOrganizationOrganizationIDWorkspaceParams{
		HTTPClient: client,
	}
}

/* PostOrganizationOrganizationIDWorkspaceParams contains all the parameters to send to the API endpoint
   for the post organization organization ID workspace operation.

   Typically these are written to a http.Request.
*/
type PostOrganizationOrganizationIDWorkspaceParams struct {

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	// Workspace.
	Workspace PostOrganizationOrganizationIDWorkspaceBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post organization organization ID workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationOrganizationIDWorkspaceParams) WithDefaults() *PostOrganizationOrganizationIDWorkspaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post organization organization ID workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationOrganizationIDWorkspaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) WithTimeout(timeout time.Duration) *PostOrganizationOrganizationIDWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) WithContext(ctx context.Context) *PostOrganizationOrganizationIDWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) WithHTTPClient(client *http.Client) *PostOrganizationOrganizationIDWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) WithOrganizationID(organizationID string) *PostOrganizationOrganizationIDWorkspaceParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithWorkspace adds the workspace to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) WithWorkspace(workspace PostOrganizationOrganizationIDWorkspaceBody) *PostOrganizationOrganizationIDWorkspaceParams {
	o.SetWorkspace(workspace)
	return o
}

// SetWorkspace adds the workspace to the post organization organization ID workspace params
func (o *PostOrganizationOrganizationIDWorkspaceParams) SetWorkspace(workspace PostOrganizationOrganizationIDWorkspaceBody) {
	o.Workspace = workspace
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganizationOrganizationIDWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Workspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
