// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteOrganizationOrganizationIDRelationshipsJobParams creates a new DeleteOrganizationOrganizationIDRelationshipsJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteOrganizationOrganizationIDRelationshipsJobParams() *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	return &DeleteOrganizationOrganizationIDRelationshipsJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrganizationOrganizationIDRelationshipsJobParamsWithTimeout creates a new DeleteOrganizationOrganizationIDRelationshipsJobParams object
// with the ability to set a timeout on a request.
func NewDeleteOrganizationOrganizationIDRelationshipsJobParamsWithTimeout(timeout time.Duration) *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	return &DeleteOrganizationOrganizationIDRelationshipsJobParams{
		timeout: timeout,
	}
}

// NewDeleteOrganizationOrganizationIDRelationshipsJobParamsWithContext creates a new DeleteOrganizationOrganizationIDRelationshipsJobParams object
// with the ability to set a context for a request.
func NewDeleteOrganizationOrganizationIDRelationshipsJobParamsWithContext(ctx context.Context) *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	return &DeleteOrganizationOrganizationIDRelationshipsJobParams{
		Context: ctx,
	}
}

// NewDeleteOrganizationOrganizationIDRelationshipsJobParamsWithHTTPClient creates a new DeleteOrganizationOrganizationIDRelationshipsJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteOrganizationOrganizationIDRelationshipsJobParamsWithHTTPClient(client *http.Client) *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	return &DeleteOrganizationOrganizationIDRelationshipsJobParams{
		HTTPClient: client,
	}
}

/* DeleteOrganizationOrganizationIDRelationshipsJobParams contains all the parameters to send to the API endpoint
   for the delete organization organization ID relationships job operation.

   Typically these are written to a http.Request.
*/
type DeleteOrganizationOrganizationIDRelationshipsJobParams struct {

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	// Relationship.
	Relationship DeleteOrganizationOrganizationIDRelationshipsJobBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete organization organization ID relationships job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) WithDefaults() *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete organization organization ID relationships job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) WithTimeout(timeout time.Duration) *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) WithContext(ctx context.Context) *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) WithHTTPClient(client *http.Client) *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) WithOrganizationID(organizationID string) *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithRelationship adds the relationship to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) WithRelationship(relationship DeleteOrganizationOrganizationIDRelationshipsJobBody) *DeleteOrganizationOrganizationIDRelationshipsJobParams {
	o.SetRelationship(relationship)
	return o
}

// SetRelationship adds the relationship to the delete organization organization ID relationships job params
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) SetRelationship(relationship DeleteOrganizationOrganizationIDRelationshipsJobBody) {
	o.Relationship = relationship
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrganizationOrganizationIDRelationshipsJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Relationship); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
