// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetOrganizationOrganizationIDRelationshipsJobReader is a Reader for the GetOrganizationOrganizationIDRelationshipsJob structure.
type GetOrganizationOrganizationIDRelationshipsJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationOrganizationIDRelationshipsJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationOrganizationIDRelationshipsJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationOrganizationIDRelationshipsJobOK creates a GetOrganizationOrganizationIDRelationshipsJobOK with default headers values
func NewGetOrganizationOrganizationIDRelationshipsJobOK() *GetOrganizationOrganizationIDRelationshipsJobOK {
	return &GetOrganizationOrganizationIDRelationshipsJobOK{}
}

/* GetOrganizationOrganizationIDRelationshipsJobOK describes a response with status code 200, with default header values.

Successful response
*/
type GetOrganizationOrganizationIDRelationshipsJobOK struct {
	Payload *GetOrganizationOrganizationIDRelationshipsJobOKBody
}

func (o *GetOrganizationOrganizationIDRelationshipsJobOK) Error() string {
	return fmt.Sprintf("[GET /organization/{organizationId}/relationships/job][%d] getOrganizationOrganizationIdRelationshipsJobOK  %+v", 200, o.Payload)
}
func (o *GetOrganizationOrganizationIDRelationshipsJobOK) GetPayload() *GetOrganizationOrganizationIDRelationshipsJobOKBody {
	return o.Payload
}

func (o *GetOrganizationOrganizationIDRelationshipsJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetOrganizationOrganizationIDRelationshipsJobOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetOrganizationOrganizationIDRelationshipsJobOKBody get organization organization ID relationships job o k body
swagger:model GetOrganizationOrganizationIDRelationshipsJobOKBody
*/
type GetOrganizationOrganizationIDRelationshipsJobOKBody struct {

	// data
	Data []*GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0 `json:"data"`
}

// Validate validates this get organization organization ID relationships job o k body
func (o *GetOrganizationOrganizationIDRelationshipsJobOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOrganizationOrganizationIDRelationshipsJobOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOrganizationOrganizationIdRelationshipsJobOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get organization organization ID relationships job o k body based on the context it is used
func (o *GetOrganizationOrganizationIDRelationshipsJobOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOrganizationOrganizationIDRelationshipsJobOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOrganizationOrganizationIdRelationshipsJobOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsJobOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsJobOKBody) UnmarshalBinary(b []byte) error {
	var res GetOrganizationOrganizationIDRelationshipsJobOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0 get organization organization ID relationships job o k body data items0
swagger:model GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0
*/
type GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0 struct {

	// id
	ID string `json:"id,omitempty"`

	// type
	// Enum: [job]
	Type string `json:"type,omitempty"`
}

// Validate validates this get organization organization ID relationships job o k body data items0
func (o *GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getOrganizationOrganizationIdRelationshipsJobOKBodyDataItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["job"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getOrganizationOrganizationIdRelationshipsJobOKBodyDataItems0TypeTypePropEnum = append(getOrganizationOrganizationIdRelationshipsJobOKBodyDataItems0TypeTypePropEnum, v)
	}
}

const (

	// GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0TypeJob captures enum value "job"
	GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0TypeJob string = "job"
)

// prop value enum
func (o *GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getOrganizationOrganizationIdRelationshipsJobOKBodyDataItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0) validateType(formats strfmt.Registry) error {
	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get organization organization ID relationships job o k body data items0 based on context it is used
func (o *GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res GetOrganizationOrganizationIDRelationshipsJobOKBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
