// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationOrganizationIDRelationshipsJobParams creates a new GetOrganizationOrganizationIDRelationshipsJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationOrganizationIDRelationshipsJobParams() *GetOrganizationOrganizationIDRelationshipsJobParams {
	return &GetOrganizationOrganizationIDRelationshipsJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationOrganizationIDRelationshipsJobParamsWithTimeout creates a new GetOrganizationOrganizationIDRelationshipsJobParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationOrganizationIDRelationshipsJobParamsWithTimeout(timeout time.Duration) *GetOrganizationOrganizationIDRelationshipsJobParams {
	return &GetOrganizationOrganizationIDRelationshipsJobParams{
		timeout: timeout,
	}
}

// NewGetOrganizationOrganizationIDRelationshipsJobParamsWithContext creates a new GetOrganizationOrganizationIDRelationshipsJobParams object
// with the ability to set a context for a request.
func NewGetOrganizationOrganizationIDRelationshipsJobParamsWithContext(ctx context.Context) *GetOrganizationOrganizationIDRelationshipsJobParams {
	return &GetOrganizationOrganizationIDRelationshipsJobParams{
		Context: ctx,
	}
}

// NewGetOrganizationOrganizationIDRelationshipsJobParamsWithHTTPClient creates a new GetOrganizationOrganizationIDRelationshipsJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationOrganizationIDRelationshipsJobParamsWithHTTPClient(client *http.Client) *GetOrganizationOrganizationIDRelationshipsJobParams {
	return &GetOrganizationOrganizationIDRelationshipsJobParams{
		HTTPClient: client,
	}
}

/* GetOrganizationOrganizationIDRelationshipsJobParams contains all the parameters to send to the API endpoint
   for the get organization organization ID relationships job operation.

   Typically these are written to a http.Request.
*/
type GetOrganizationOrganizationIDRelationshipsJobParams struct {

	/* FilterJob.

	   Filters the collection of job using a 'disjoint' RSQL expression
	*/
	FilterJob *string

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	/* PageLimit.

	   Maximum number of items to return.  Can be used with page[offset]
	*/
	PageLimit *int64

	/* PageNumber.

	   Number of pages to return.  Can be used with page[size]
	*/
	PageNumber *int64

	/* PageOffset.

	   Offset from 0 to start paginating.  Can be used with page[limit]
	*/
	PageOffset *int64

	/* PageSize.

	   Number of elements per page.  Can be used with page[number]
	*/
	PageSize *int64

	/* PageTotals.

	   For requesting total pages/records be included in the response page meta data
	*/
	PageTotals *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organization organization ID relationships job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithDefaults() *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organization organization ID relationships job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithTimeout(timeout time.Duration) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithContext(ctx context.Context) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithHTTPClient(client *http.Client) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilterJob adds the filterJob to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithFilterJob(filterJob *string) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetFilterJob(filterJob)
	return o
}

// SetFilterJob adds the filterJob to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetFilterJob(filterJob *string) {
	o.FilterJob = filterJob
}

// WithOrganizationID adds the organizationID to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithOrganizationID(organizationID string) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithPageLimit adds the pageLimit to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithPageLimit(pageLimit *int64) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetPageLimit(pageLimit)
	return o
}

// SetPageLimit adds the pageLimit to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetPageLimit(pageLimit *int64) {
	o.PageLimit = pageLimit
}

// WithPageNumber adds the pageNumber to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithPageNumber(pageNumber *int64) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetPageNumber(pageNumber)
	return o
}

// SetPageNumber adds the pageNumber to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetPageNumber(pageNumber *int64) {
	o.PageNumber = pageNumber
}

// WithPageOffset adds the pageOffset to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithPageOffset(pageOffset *int64) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetPageOffset(pageOffset)
	return o
}

// SetPageOffset adds the pageOffset to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetPageOffset(pageOffset *int64) {
	o.PageOffset = pageOffset
}

// WithPageSize adds the pageSize to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithPageSize(pageSize *int64) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithPageTotals adds the pageTotals to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WithPageTotals(pageTotals *string) *GetOrganizationOrganizationIDRelationshipsJobParams {
	o.SetPageTotals(pageTotals)
	return o
}

// SetPageTotals adds the pageTotals to the get organization organization ID relationships job params
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) SetPageTotals(pageTotals *string) {
	o.PageTotals = pageTotals
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationOrganizationIDRelationshipsJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FilterJob != nil {

		// query param filter[job]
		var qrFilterJob string

		if o.FilterJob != nil {
			qrFilterJob = *o.FilterJob
		}
		qFilterJob := qrFilterJob
		if qFilterJob != "" {

			if err := r.SetQueryParam("filter[job]", qFilterJob); err != nil {
				return err
			}
		}
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if o.PageLimit != nil {

		// query param page[limit]
		var qrPageLimit int64

		if o.PageLimit != nil {
			qrPageLimit = *o.PageLimit
		}
		qPageLimit := swag.FormatInt64(qrPageLimit)
		if qPageLimit != "" {

			if err := r.SetQueryParam("page[limit]", qPageLimit); err != nil {
				return err
			}
		}
	}

	if o.PageNumber != nil {

		// query param page[number]
		var qrPageNumber int64

		if o.PageNumber != nil {
			qrPageNumber = *o.PageNumber
		}
		qPageNumber := swag.FormatInt64(qrPageNumber)
		if qPageNumber != "" {

			if err := r.SetQueryParam("page[number]", qPageNumber); err != nil {
				return err
			}
		}
	}

	if o.PageOffset != nil {

		// query param page[offset]
		var qrPageOffset int64

		if o.PageOffset != nil {
			qrPageOffset = *o.PageOffset
		}
		qPageOffset := swag.FormatInt64(qrPageOffset)
		if qPageOffset != "" {

			if err := r.SetQueryParam("page[offset]", qPageOffset); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page[size]
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page[size]", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.PageTotals != nil {

		// query param page[totals]
		var qrPageTotals string

		if o.PageTotals != nil {
			qrPageTotals = *o.PageTotals
		}
		qPageTotals := qrPageTotals
		if qPageTotals != "" {

			if err := r.SetQueryParam("page[totals]", qPageTotals); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
