// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationOrganizationIDJobParams creates a new GetOrganizationOrganizationIDJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationOrganizationIDJobParams() *GetOrganizationOrganizationIDJobParams {
	return &GetOrganizationOrganizationIDJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationOrganizationIDJobParamsWithTimeout creates a new GetOrganizationOrganizationIDJobParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationOrganizationIDJobParamsWithTimeout(timeout time.Duration) *GetOrganizationOrganizationIDJobParams {
	return &GetOrganizationOrganizationIDJobParams{
		timeout: timeout,
	}
}

// NewGetOrganizationOrganizationIDJobParamsWithContext creates a new GetOrganizationOrganizationIDJobParams object
// with the ability to set a context for a request.
func NewGetOrganizationOrganizationIDJobParamsWithContext(ctx context.Context) *GetOrganizationOrganizationIDJobParams {
	return &GetOrganizationOrganizationIDJobParams{
		Context: ctx,
	}
}

// NewGetOrganizationOrganizationIDJobParamsWithHTTPClient creates a new GetOrganizationOrganizationIDJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationOrganizationIDJobParamsWithHTTPClient(client *http.Client) *GetOrganizationOrganizationIDJobParams {
	return &GetOrganizationOrganizationIDJobParams{
		HTTPClient: client,
	}
}

/* GetOrganizationOrganizationIDJobParams contains all the parameters to send to the API endpoint
   for the get organization organization ID job operation.

   Typically these are written to a http.Request.
*/
type GetOrganizationOrganizationIDJobParams struct {

	/* FieldsJob.

	   Selects the set of job fields that should be returned in the result.
	*/
	FieldsJob []string

	/* FilterJob.

	   Filters the collection of job using a 'disjoint' RSQL expression
	*/
	FilterJob *string

	/* Include.

	   Selects the set of relationships that should be expanded as a compound document in the result.
	*/
	Include []string

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	/* PageLimit.

	   Maximum number of items to return.  Can be used with page[offset]
	*/
	PageLimit *int64

	/* PageNumber.

	   Number of pages to return.  Can be used with page[size]
	*/
	PageNumber *int64

	/* PageOffset.

	   Offset from 0 to start paginating.  Can be used with page[limit]
	*/
	PageOffset *int64

	/* PageSize.

	   Number of elements per page.  Can be used with page[number]
	*/
	PageSize *int64

	/* PageTotals.

	   For requesting total pages/records be included in the response page meta data
	*/
	PageTotals *string

	/* Sort.

	   Sorts the collection on the selected attributes.  A prefix of '-' sorts descending
	*/
	Sort []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organization organization ID job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationOrganizationIDJobParams) WithDefaults() *GetOrganizationOrganizationIDJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organization organization ID job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationOrganizationIDJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithTimeout(timeout time.Duration) *GetOrganizationOrganizationIDJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithContext(ctx context.Context) *GetOrganizationOrganizationIDJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithHTTPClient(client *http.Client) *GetOrganizationOrganizationIDJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFieldsJob adds the fieldsJob to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithFieldsJob(fieldsJob []string) *GetOrganizationOrganizationIDJobParams {
	o.SetFieldsJob(fieldsJob)
	return o
}

// SetFieldsJob adds the fieldsJob to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetFieldsJob(fieldsJob []string) {
	o.FieldsJob = fieldsJob
}

// WithFilterJob adds the filterJob to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithFilterJob(filterJob *string) *GetOrganizationOrganizationIDJobParams {
	o.SetFilterJob(filterJob)
	return o
}

// SetFilterJob adds the filterJob to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetFilterJob(filterJob *string) {
	o.FilterJob = filterJob
}

// WithInclude adds the include to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithInclude(include []string) *GetOrganizationOrganizationIDJobParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetInclude(include []string) {
	o.Include = include
}

// WithOrganizationID adds the organizationID to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithOrganizationID(organizationID string) *GetOrganizationOrganizationIDJobParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithPageLimit adds the pageLimit to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithPageLimit(pageLimit *int64) *GetOrganizationOrganizationIDJobParams {
	o.SetPageLimit(pageLimit)
	return o
}

// SetPageLimit adds the pageLimit to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetPageLimit(pageLimit *int64) {
	o.PageLimit = pageLimit
}

// WithPageNumber adds the pageNumber to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithPageNumber(pageNumber *int64) *GetOrganizationOrganizationIDJobParams {
	o.SetPageNumber(pageNumber)
	return o
}

// SetPageNumber adds the pageNumber to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetPageNumber(pageNumber *int64) {
	o.PageNumber = pageNumber
}

// WithPageOffset adds the pageOffset to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithPageOffset(pageOffset *int64) *GetOrganizationOrganizationIDJobParams {
	o.SetPageOffset(pageOffset)
	return o
}

// SetPageOffset adds the pageOffset to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetPageOffset(pageOffset *int64) {
	o.PageOffset = pageOffset
}

// WithPageSize adds the pageSize to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithPageSize(pageSize *int64) *GetOrganizationOrganizationIDJobParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithPageTotals adds the pageTotals to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithPageTotals(pageTotals *string) *GetOrganizationOrganizationIDJobParams {
	o.SetPageTotals(pageTotals)
	return o
}

// SetPageTotals adds the pageTotals to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetPageTotals(pageTotals *string) {
	o.PageTotals = pageTotals
}

// WithSort adds the sort to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) WithSort(sort []string) *GetOrganizationOrganizationIDJobParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get organization organization ID job params
func (o *GetOrganizationOrganizationIDJobParams) SetSort(sort []string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationOrganizationIDJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FieldsJob != nil {

		// binding items for fields[job]
		joinedFieldsJob := o.bindParamFieldsJob(reg)

		// query array param fields[job]
		if err := r.SetQueryParam("fields[job]", joinedFieldsJob...); err != nil {
			return err
		}
	}

	if o.FilterJob != nil {

		// query param filter[job]
		var qrFilterJob string

		if o.FilterJob != nil {
			qrFilterJob = *o.FilterJob
		}
		qFilterJob := qrFilterJob
		if qFilterJob != "" {

			if err := r.SetQueryParam("filter[job]", qFilterJob); err != nil {
				return err
			}
		}
	}

	if o.Include != nil {

		// binding items for include
		joinedInclude := o.bindParamInclude(reg)

		// query array param include
		if err := r.SetQueryParam("include", joinedInclude...); err != nil {
			return err
		}
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if o.PageLimit != nil {

		// query param page[limit]
		var qrPageLimit int64

		if o.PageLimit != nil {
			qrPageLimit = *o.PageLimit
		}
		qPageLimit := swag.FormatInt64(qrPageLimit)
		if qPageLimit != "" {

			if err := r.SetQueryParam("page[limit]", qPageLimit); err != nil {
				return err
			}
		}
	}

	if o.PageNumber != nil {

		// query param page[number]
		var qrPageNumber int64

		if o.PageNumber != nil {
			qrPageNumber = *o.PageNumber
		}
		qPageNumber := swag.FormatInt64(qrPageNumber)
		if qPageNumber != "" {

			if err := r.SetQueryParam("page[number]", qPageNumber); err != nil {
				return err
			}
		}
	}

	if o.PageOffset != nil {

		// query param page[offset]
		var qrPageOffset int64

		if o.PageOffset != nil {
			qrPageOffset = *o.PageOffset
		}
		qPageOffset := swag.FormatInt64(qrPageOffset)
		if qPageOffset != "" {

			if err := r.SetQueryParam("page[offset]", qPageOffset); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page[size]
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page[size]", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.PageTotals != nil {

		// query param page[totals]
		var qrPageTotals string

		if o.PageTotals != nil {
			qrPageTotals = *o.PageTotals
		}
		qPageTotals := qrPageTotals
		if qPageTotals != "" {

			if err := r.SetQueryParam("page[totals]", qPageTotals); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// binding items for sort
		joinedSort := o.bindParamSort(reg)

		// query array param sort
		if err := r.SetQueryParam("sort", joinedSort...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetOrganizationOrganizationIDJob binds the parameter fields[job]
func (o *GetOrganizationOrganizationIDJobParams) bindParamFieldsJob(formats strfmt.Registry) []string {
	fieldsJobIR := o.FieldsJob

	var fieldsJobIC []string
	for _, fieldsJobIIR := range fieldsJobIR { // explode []string

		fieldsJobIIV := fieldsJobIIR // string as string
		fieldsJobIC = append(fieldsJobIC, fieldsJobIIV)
	}

	// items.CollectionFormat: "csv"
	fieldsJobIS := swag.JoinByFormat(fieldsJobIC, "csv")

	return fieldsJobIS
}

// bindParamGetOrganizationOrganizationIDJob binds the parameter include
func (o *GetOrganizationOrganizationIDJobParams) bindParamInclude(formats strfmt.Registry) []string {
	includeIR := o.Include

	var includeIC []string
	for _, includeIIR := range includeIR { // explode []string

		includeIIV := includeIIR // string as string
		includeIC = append(includeIC, includeIIV)
	}

	// items.CollectionFormat: "csv"
	includeIS := swag.JoinByFormat(includeIC, "csv")

	return includeIS
}

// bindParamGetOrganizationOrganizationIDJob binds the parameter sort
func (o *GetOrganizationOrganizationIDJobParams) bindParamSort(formats strfmt.Registry) []string {
	sortIR := o.Sort

	var sortIC []string
	for _, sortIIR := range sortIR { // explode []string

		sortIIV := sortIIR // string as string
		sortIC = append(sortIC, sortIIV)
	}

	// items.CollectionFormat: "csv"
	sortIS := swag.JoinByFormat(sortIC, "csv")

	return sortIS
}
