// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostOrganizationOrganizationIDJobParams creates a new PostOrganizationOrganizationIDJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOrganizationOrganizationIDJobParams() *PostOrganizationOrganizationIDJobParams {
	return &PostOrganizationOrganizationIDJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganizationOrganizationIDJobParamsWithTimeout creates a new PostOrganizationOrganizationIDJobParams object
// with the ability to set a timeout on a request.
func NewPostOrganizationOrganizationIDJobParamsWithTimeout(timeout time.Duration) *PostOrganizationOrganizationIDJobParams {
	return &PostOrganizationOrganizationIDJobParams{
		timeout: timeout,
	}
}

// NewPostOrganizationOrganizationIDJobParamsWithContext creates a new PostOrganizationOrganizationIDJobParams object
// with the ability to set a context for a request.
func NewPostOrganizationOrganizationIDJobParamsWithContext(ctx context.Context) *PostOrganizationOrganizationIDJobParams {
	return &PostOrganizationOrganizationIDJobParams{
		Context: ctx,
	}
}

// NewPostOrganizationOrganizationIDJobParamsWithHTTPClient creates a new PostOrganizationOrganizationIDJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOrganizationOrganizationIDJobParamsWithHTTPClient(client *http.Client) *PostOrganizationOrganizationIDJobParams {
	return &PostOrganizationOrganizationIDJobParams{
		HTTPClient: client,
	}
}

/* PostOrganizationOrganizationIDJobParams contains all the parameters to send to the API endpoint
   for the post organization organization ID job operation.

   Typically these are written to a http.Request.
*/
type PostOrganizationOrganizationIDJobParams struct {

	// Job.
	Job PostOrganizationOrganizationIDJobBody

	/* OrganizationID.

	   organization Identifier
	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post organization organization ID job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationOrganizationIDJobParams) WithDefaults() *PostOrganizationOrganizationIDJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post organization organization ID job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationOrganizationIDJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) WithTimeout(timeout time.Duration) *PostOrganizationOrganizationIDJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) WithContext(ctx context.Context) *PostOrganizationOrganizationIDJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) WithHTTPClient(client *http.Client) *PostOrganizationOrganizationIDJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJob adds the job to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) WithJob(job PostOrganizationOrganizationIDJobBody) *PostOrganizationOrganizationIDJobParams {
	o.SetJob(job)
	return o
}

// SetJob adds the job to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) SetJob(job PostOrganizationOrganizationIDJobBody) {
	o.Job = job
}

// WithOrganizationID adds the organizationID to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) WithOrganizationID(organizationID string) *PostOrganizationOrganizationIDJobParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the post organization organization ID job params
func (o *PostOrganizationOrganizationIDJobParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganizationOrganizationIDJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Job); err != nil {
		return err
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
